language: python
python: "2.7"
install:
    - "pip install coveralls"
cache: pip
# Use docker for builds
sudo: false
script:
    - make validate
    - git fetch origin master:refs/remotes/origin/master # https://github.com/edx/diff-cover#troubleshooting
    - make diff.report
branches:
    only:
      - master
after_success:
    - coveralls
    - bash ./scripts/build-stats-to-datadog.sh
